export const FRAME_CONTENT_SCHEMA = {
  issueNum: { aliases: ['issueNum', 'issue_num', 'issue', 'issueNumber'], type: 'string' },
  date: { aliases: ['date', 'publishedAt', 'published_at'], type: 'string' },
  desk: { aliases: ['desk', 'section'], type: 'string' },
  volume: { aliases: ['volume', 'vol'], type: 'string' },
  topicTag: { aliases: ['topicTag', 'topic_tag', 'topic'], type: 'string' },
  title: { aliases: ['title', 'headline'], type: 'string' },
  deck: { aliases: ['deck', 'subhead', 'subtitle'], type: 'string' },
  body: { aliases: ['body', 'content', 'summary'], type: 'string' },
  handle: { aliases: ['handle', 'authorHandle'], type: 'string' },
  socialX: { aliases: ['socialX', 'xHandle'], type: 'string' },
  socialSub: { aliases: ['socialSub', 'substackHandle'], type: 'string' },
  status: { aliases: ['status'], type: 'string' },
  tickerSpeed: { aliases: ['tickerSpeed', 'ticker_speed'], type: 'number' },
  sparkData: { aliases: ['sparkData', 'spark_data'], type: 'string' },
  stats: { aliases: ['stats'], type: 'statArray' },
  tableRows: { aliases: ['tableRows', 'table_rows'], type: 'tableRows' },
  tableHeaders: { aliases: ['tableHeaders', 'table_headers'], type: 'stringArray' },
  bullPoints: { aliases: ['bullPoints', 'bull_points'], type: 'stringArray' },
  bearPoints: { aliases: ['bearPoints', 'bear_points'], type: 'stringArray' },
  bigNumber: { aliases: ['bigNumber', 'big_number'], type: 'string' },
  bigLabel: { aliases: ['bigLabel', 'big_label'], type: 'string' },
  verdict: { aliases: ['verdict'], type: 'string' },
  gridItems: { aliases: ['gridItems', 'grid_items'], type: 'gridItems' },
  timelineEvents: { aliases: ['timelineEvents', 'timeline_events'], type: 'timelineEvents' },
  nextDrop: { aliases: ['nextDrop', 'next_drop'], type: 'string' },
  pullQuote: { aliases: ['pullQuote', 'pull_quote'], type: 'string' },
  heroUrl: { aliases: ['heroUrl', 'hero_url'], type: 'string' },
  logoUrl: { aliases: ['logoUrl', 'logo_url'], type: 'string' },
  sourceLinks: { aliases: ['sourceLinks', 'source_links', 'sources'], type: 'string' },
  evidenceLedger: { aliases: ['evidenceLedger', 'evidence_ledger', 'ledger'], type: 'object' },
};

export const EDITOR_STATE_SCHEMA = {
  frameId: { aliases: ['frameId', 'frame_id'], type: 'number' },
  theme: { aliases: ['theme'], type: 'object' },
  content: { aliases: ['content', 'frameContent'], type: 'content' },
  overrides: { aliases: ['overrides', 'styleOverrides'], type: 'object' },
  aspectRatio: { aliases: ['aspectRatio', 'aspect_ratio'], type: 'object' },
  bgGradient: { aliases: ['bgGradient', 'bg_gradient'], type: 'objectOrNull' },
  patternOverlay: { aliases: ['patternOverlay', 'pattern_overlay'], type: 'objectOrNull' },
};
