import {
  TierListLayout, PostmortemLayout, TrustStackLayout, PitchDeckLayout, MechanismLayout, ThesisLayout,
  CoverStoryLayout, ReceiptLayout, GlossaryLayout, MatrixLayout, ThreatModelLayout, FailureTreeLayout,
  FounderLayout, AnatomyLayout, FlowLayout, BracketLayout, ThreeLayerLayout, LongBetLayout,
  OrgChartLayout, PeriodicLayout, CurveLayout, FieldGuideLayout, MentalModelLayout, SubwayLayout,
  ConstellationLayout, StackLayout, TradeRoutesLayout,
} from '../FrameShell';

export const extendedLayouts = {
  'tier-list': TierListLayout,
  postmortem: PostmortemLayout,
  'trust-stack': TrustStackLayout,
  'pitch-deck': PitchDeckLayout,
  mechanism: MechanismLayout,
  thesis: ThesisLayout,
  'cover-story': CoverStoryLayout,
  receipt: ReceiptLayout,
  glossary: GlossaryLayout,
  matrix: MatrixLayout,
  'threat-model': ThreatModelLayout,
  'failure-tree': FailureTreeLayout,
  founder: FounderLayout,
  anatomy: AnatomyLayout,
  flow: FlowLayout,
  bracket: BracketLayout,
  'three-layer': ThreeLayerLayout,
  'long-bet': LongBetLayout,
  'org-chart': OrgChartLayout,
  periodic: PeriodicLayout,
  curve: CurveLayout,
  'field-guide': FieldGuideLayout,
  'mental-model': MentalModelLayout,
  subway: SubwayLayout,
  constellation: ConstellationLayout,
  stack: StackLayout,
  'trade-routes': TradeRoutesLayout,
};
